In [51]:
import numpy as np
import pylab

def myprint(i):
    print(type(i))
    print(i)
    print(np.linalg.matrix_rank(i))


i0=np.full((2,3),5.0)
i0[1,0]=1
myprint(i0)
i0[1:2] = 1
myprint(i0)

<class 'numpy.ndarray'>
[[5. 5. 5.]
 [1. 5. 5.]]
2
<class 'numpy.ndarray'>
[[5. 5. 5.]
 [1. 1. 1.]]
1


In [17]:
i1=np.eye(3)
myprint(i1);

i2=np.matrix(i1)
myprint(i2);




<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3
<class 'numpy.matrix'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3


In [57]:
 a = np.arange(12)
aa = a**2
print(a)
print(aa)
i = np.array( [ 1,1,3,8,5 ] )
print(i)
print(aa[i])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[  0   1   4   9  16  25  36  49  64  81 100 121]
[1 1 3 8 5]
[ 1  1  9 64 25]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 用布尔值来索引：

In [50]:
print(a>4)
a[a>4]=0
print(a)

[False False False False False  True  True  True  True  True  True  True]
[0 1 2 3 4 0 0 0 0 0 0 0]


# ix_()

In [83]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
d = np.ix_(a,b,c)
print(d)


(array([[[2]],

       [[3]],

       [[4]],

       [[5]]]), array([[[8],
        [5],
        [4]]]), array([[[5, 4, 6, 8, 3]]]))
