In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
out.backward()

In [8]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [10]:
print(x.grad) 
print(y.retain_grad())

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


# 另一个雅可比向量积的例子

In [14]:
x = torch.randn(3, requires_grad=True)
y = x*2
print(x, y)

tensor([ 0.1848, -1.6411,  0.4399], requires_grad=True) tensor([ 0.3696, -3.2822,  0.8798], grad_fn=<MulBackward0>)


In [24]:
y=y*2
print(y)
print(y.data.norm())


tensor([  2.9566, -26.2573,   7.0387], grad_fn=<MulBackward0>)
tensor(27.3446)


In [26]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

In [28]:
print(y)
print(x.grad)

tensor([  2.9566, -26.2573,   7.0387], grad_fn=<MulBackward0>)
tensor([1.6000e+00, 1.6000e+01, 1.6000e-03])
