In [1]:
import torch
import torchvision
print(torch)
print(torchvision)
torch.rand(3,5)

<module 'torch' from '/home/wenbin/pyvenv/ml/lib/python3.7/site-packages/torch/__init__.py'>
<module 'torchvision' from '/home/wenbin/pyvenv/ml/lib/python3.7/site-packages/torchvision/__init__.py'>


tensor([[0.1699, 0.2107, 0.6919, 0.4724, 0.1464],
        [0.8945, 0.7386, 0.2728, 0.7790, 0.4416],
        [0.6816, 0.7786, 0.6324, 0.7491, 0.7286]])

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:


x = x.new_ones(5, 3, dtype=torch.double)    

# new_* methods take in sizes
print(x)


x = torch.randn_like(x, dtype=torch.float)  

# override dtype!
print(x)                                    


result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)


# result has the same size



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4835,  0.3349, -0.7775],
        [ 0.2293,  0.9957, -1.7917],
        [ 0.1282, -0.3381, -0.8351],
        [-0.0044,  0.5020,  0.0821],
        [ 0.5042, -0.8222,  0.5606]])


In [9]:


y = torch.rand(5, 3)
print(x + y)  #方式1
print(torch.add(x, y))  #方式2

#方式3
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)


# adds x to y
y.add_(x)
print(y)


tensor([[ 0.6145,  1.1860, -0.2074],
        [ 0.9967,  1.4342, -1.6493],
        [ 0.1644, -0.1836,  0.0405],
        [ 0.4860,  1.1370,  0.6028],
        [ 1.0587,  0.0252,  1.1134]])
tensor([[ 0.6145,  1.1860, -0.2074],
        [ 0.9967,  1.4342, -1.6493],
        [ 0.1644, -0.1836,  0.0405],
        [ 0.4860,  1.1370,  0.6028],
        [ 1.0587,  0.0252,  1.1134]])
tensor([[ 0.6145,  1.1860, -0.2074],
        [ 0.9967,  1.4342, -1.6493],
        [ 0.1644, -0.1836,  0.0405],
        [ 0.4860,  1.1370,  0.6028],
        [ 1.0587,  0.0252,  1.1134]])
tensor([[ 0.6145,  1.1860, -0.2074],
        [ 0.9967,  1.4342, -1.6493],
        [ 0.1644, -0.1836,  0.0405],
        [ 0.4860,  1.1370,  0.6028],
        [ 1.0587,  0.0252,  1.1134]])


In [10]:


x = torch.randn(1)
print(x)
print(x.item())



tensor([-0.7824])
-0.7824291586875916
