In [376]:
import numpy as np
def sampling(probDistribution,size=10000):
    decimal=np.log10(size).astype(int)
    p_array = np.array(probDistribution)
    p_array_arounded = (np.around(p_array,decimal) * size).astype(int)
    if(p_array_arounded.sum()!=size):
        print("It's not a correct probDistribution:{}".format(p_array_arounded.sum()))
#     else:
#         print("p_array_arounded:{}".format(p_array_arounded))

    rand_array=np.zeros(size).astype(int)
    offset=0;
#     print(rand_array)
    for i in range(len(p_array_arounded)):
#         print("i:{}".format(i))
#         print(p_array_arounded[i])
        rand_array[offset:offset+p_array_arounded[i]]=i+1
        offset+=p_array_arounded[i]
        
#     print("rand_array:{}".format(rand_array))        
    sample_id=np.random.randint(0,size)
#     print("sample_id:{}".format(sample_id))
    return rand_array[sample_id]


In [388]:
def hmmGenerate(A,B,PI,T):
        states=np.zeros(T).astype(int)
        observes=np.zeros(T).astype(int)
        qi=sampling(PI)
#         print("qi:{}".format(qi))
        for t in range(T):
            states[t]=qi
            observes[t]=sampling(B[qi-1])
            qi=sampling(A[qi-1])
        return (states,observes)

In [378]:
# test sampling
total=0;
for i in range(5):
    s1 = sampling([0.5,0.5],10)
    total+=s1-1
print(total)

3


In [429]:
#test sampling
# s1 = sampling([0.4234,0.1245, 0.4645345],100,2)
# print(s1)
def f(M, O):
#     print(M)
#     print(O)
    result = np.array([M[x-1] for x in O])
#     print(result)
    return result

N=[1,2]
M=['正','反']
A=np.array([[0.8,0.2],[0.8,0.2]])
B=np.array([[0.8,0.2],[0.5,0.5]])
PI=[0.8,0.2]
T=100

(S,O)=hmmGenerate(A,B,PI,T)
print("S:{}".format(S))
print("O:{}".format(O))


qi:1
S:[1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 2 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1 1 2 2 2 1 1 1 1 2 2 2 1 2 1 2 1
 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1]
O:[2 2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 1 1 1 1 2 1 2 1 2 2 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 1 2 1 2 2 1 2 2 2 2 1 1 1 1 2 1 2 1 2 1 1 1 1 1 2 1 1 1 1 2 1
 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1]


In [430]:
# print(len(S[S==2]))
# print(len(O[S==2]))
print(len(O[S==2]))
O1=O[S==1]
O2=O[S==2]
print(O1)
print(O2)
print(len(O2[O2==2]))
a=np.array([[len(O1[O1==1]), len(O1[O1==2])],[len(O2[O2==1]), len(O2[O2==2])]])
print(a)
b=np.array([[0.,0.],[0.,0.]])
b[0]=a[0]/a[0].sum()
b[1]=a[1]/a[1].sum()

print(b)

20
[2 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 2 1 2 2 1 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 2 1 1 1 1 1 1 1
 1 1 1 1 1 1]
[2 2 2 2 2 1 1 2 2 1 2 1 2 1 2 1 1 2 1 2]
12
[[66 14]
 [ 8 12]]
[[0.825 0.175]
 [0.4   0.6  ]]


In [216]:
np.log10(100).astype(int)

2