In [17]:
import numpy as np

t0=np.array([0.1, 0.2, 0.7])

print(t0.shape)

p=np.array([
    [0.9, 0.075, 0.025],
    [0.15,0.8,0.05],
    [0.25,0.25,0.5]
])

print(p.shape)
# t1=t0
t1=p
for i in range(25):
    t1=np.dot(t1,p)
    print("{}: {}".format(i, t1))

# print(t0)
# print(sum(t1))

# print(0.1*0.9+0.2*0.15+0.25*0.7)

(3,)
(3, 3)
0: [[0.8275  0.13375 0.03875]
 [0.2675  0.66375 0.06875]
 [0.3875  0.34375 0.26875]]
1: [[0.7745  0.17875 0.04675]
 [0.3575  0.56825 0.07425]
 [0.4675  0.37125 0.16125]]
2: [[0.73555  0.212775 0.051675]
 [0.42555  0.499975 0.074475]
 [0.51675  0.372375 0.110875]]
3: [[0.70683  0.238305 0.054865]
 [0.47661  0.450515 0.072875]
 [0.54865  0.364375 0.086975]]
4: [[0.685609  0.2573725 0.0570185]
 [0.514745  0.4143765 0.0708785]
 [0.570185  0.3543925 0.0754225]]
5: [[0.6699086 0.2715733 0.0585181]
 [0.5431466 0.3878267 0.0690267]
 [0.585181  0.3451335 0.0696855]]
6: [[0.65828326 0.28213131 0.05958543]
 [0.56426262 0.36825403 0.06748335]
 [0.5958543  0.33741675 0.06672895]]
7: [[0.64967099 0.28997265 0.06035636]
 [0.5799453  0.35379376 0.06626094]
 [0.60356362 0.33130471 0.06513167]]
8: [[0.64328888 0.29579253 0.06091859]
 [0.59158507 0.34309614 0.06531879]
 [0.60918588 0.32659396 0.06422016]]
9: [[0.63855852 0.30011034 0.06133114]
 [0.60022068 0.33517549 0.06460383]
 [0.61331143 

In [31]:
print(t0)
print(p)
t1= np.dot(t0,p)
print(t1)
print(p.T)

t2 = np.dot(t1,p.T)
print(t2)
print(0.625*0.075)
print(0.313*0.15)

[0.1 0.2 0.7]
[[0.9   0.075 0.025]
 [0.15  0.8   0.05 ]
 [0.25  0.25  0.5  ]]
[0.295  0.3425 0.3625]
[[0.9   0.15  0.25 ]
 [0.075 0.8   0.25 ]
 [0.025 0.05  0.5  ]]
[0.30025  0.336375 0.340625]
0.046875
0.04695
