In [2]:
class Car:
    price=0.0
    capacity=0.0

    def __init__(self, price, capacity):
        self.capacity = capacity
        self.price = price

import math
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


def min_capacity(car_list):
    min_c = 10000000000;
    for car in car_list:
        if (min_c > car.capacity):
            min_c = car.capacity
    return min_c


def price(count_list, car_list):
    price_result = 0;
    for index, car in enumerate(car_list):
        price_result += car.price * count_list[index]
    return price_result


def capacity(count_list, car_list):
    capacity_result = 0;
    for index, car in enumerate(car_list):
        capacity_result+= car.capacity * count_list[index]
    return capacity_result


def main():
    print("start")

    totalPerson = 100
    car3= Car(50, 4)
    car2 = Car(120, 12)
    car1 = Car(160, 18)

    car_list = []
    car_list.append(car1)
    car_list.append(car2)
    car_list.append(car3)

    max_count = {}
    for car in car_list:
        max_count[car] = math.ceil(totalPerson / car.capacity)

    n1 = 0
    n2 = 0
    n3 = 0

    max_n1 = math.ceil(totalPerson / car1.capacity)
    max_n2 = math.ceil(totalPerson / car2.capacity)
    max_n3 = math.ceil(totalPerson / car3.capacity)

    # searchSpace = np.array([['1','2','3','费用','容量','最划算？']])
    searchSpace = np.array([[1,2,3,4,5,6]])

    for n1 in range(max_n1, -1, -1):
        for n2 in range(max_n2, -1, -1):
            for n3 in range(max_n3, -1, -1):
                if ((totalPerson < (n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity)
                     or totalPerson == (n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity))
                        and totalPerson + min_capacity(car_list) > (
                                n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity)):
                    p = price([n1, n2, n3], car_list)
                    searchSpace =np.append(searchSpace, [[n1, n2, n3, p, capacity([n1, n2, n3], car_list),0]],axis=0 )

    searchSpace[1:,5] = (searchSpace[1:,3] == min(searchSpace[1:,3]))
    print(searchSpace)

def main1():
    print("start")

    totalPerson = 100
    car1 = Car(50, 4)
    car2 = Car(120, 12)
    car3 = Car(160, 18)

    car_list = []
    car_list.append(car1)
    car_list.append(car2)
    car_list.append(car3)

    max_count = {}
    for car in car_list:
        max_count[car] = math.ceil(totalPerson / car.capacity)

    n1 = 0
    n2 = 0
    n3 = 0

    max_n1 = math.ceil(totalPerson / car1.capacity)
    max_n2 = math.ceil(totalPerson / car2.capacity)
    max_n3 = math.ceil(totalPerson / car3.capacity)

    searchSpace = []

    for n1 in range(max_n1, -1, -1):
        for n2 in range(max_n2, -1, -1):
            for n3 in range(max_n3, -1, -1):
                if ((totalPerson < (n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity)
                     or totalPerson == (n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity))
                        and totalPerson + min_capacity(car_list) > (
                                n1 * car1.capacity + n2 * car2.capacity + n3 * car3.capacity)):
                    searchSpace.append([n1, n2, n3, price([n1, n2, n3], car_list)])

    a = np.asarray(searchSpace)
    data = a[a[:, 2] == 0][:, [0, 1, 3]]
    print(data)

    # draw
    x = data[:, 0]
    y = data[:, 1]
    p = data[:, 2]
    #
    ax = plt.subplot(111)
    ax.scatter(x, y, s = p - 2 / 3 * min(p), c=p - min(p))
    ax.set_xlabel('car1')
    ax.set_ylabel('car2')
    for i,xx in enumerate(x):
        plt.text(x[i], y[i] + 0.2, '%.0f' % p[i], ha='center', va='bottom', fontsize=11)
    # ax.set_zlabel('price')
    plt.show()

    fig = plt.figure()  # 创建一张图片
    ax3d = Axes3D(fig)
    xx, yy = np.meshgrid(x,y)
    ax3d.plot_surface(xx,yy,f(xx,yy, data),rstride=1,cstride=1,cmap=plt.cm.spring)#cmap还可以是summer autumn winter也可以自己配置
    plt.show()

def f(xx,yy, data):
    zz = np.array([xx.ravel(), yy.ravel()])
    # print(zz.T.shape)
    # print(data[:,[0,1]].T.shape)
    # print(zz.T)
    result = np.array([])
    print(result.shape)
    for i in range(0, zz.shape[1]):
        filter = (data[:, [0, 1]] == zz.T[i])[:, 0] & (data[:, [0, 1]] == zz.T[i])[:, 1]
        #     print(filter)
        if (filter.any()):
            #         print(data[filter][0,2])
            result = np.append(result, data[filter][0, 2])
        #         print(result)
        else:
            result = np.append(result, 0)
    print(result.shape)
    result.shape = (9, 9)
    print(result)
    return result

if __name__ == "__main__":
    main()


start
[[   1    2    3    4    5    6]
 [   5    1    0  920  102    1]
 [   5    0    3  950  102    0]
 [   4    2    1  930  100    0]
 [   4    1    4  960  100    0]
 [   4    0    7  990  100    0]
 [   3    4    0  960  102    0]
 [   3    3    3  990  102    0]
 [   3    2    6 1020  102    0]
 [   3    1    9 1050  102    0]
 [   3    0   12 1080  102    0]
 [   2    5    1  970  100    0]
 [   2    4    4 1000  100    0]
 [   2    3    7 1030  100    0]
 [   2    2   10 1060  100    0]
 [   2    1   13 1090  100    0]
 [   2    0   16 1120  100    0]
 [   1    7    0 1000  102    0]
 [   1    6    3 1030  102    0]
 [   1    5    6 1060  102    0]
 [   1    4    9 1090  102    0]
 [   1    3   12 1120  102    0]
 [   1    2   15 1150  102    0]
 [   1    1   18 1180  102    0]
 [   1    0   21 1210  102    0]
 [   0    8    1 1010  100    0]
 [   0    7    4 1040  100    0]
 [   0    6    7 1070  100    0]
 [   0    5   10 1100  100    0]
 [   0    4   13 1130  100    0]
 [  